### PR TITLE
Update latest ruby versions

### PR DESCRIPTION
**Pull request by colorbox**
Hi ✋
This PR updated latest ruby versions on `converter.rb`.
c.f.)https://www.ruby-lang.org/en/downloads/releases/

Thank you nice gem 👍

### CODE REVIEW

**Comment by colorbox** [comment]
sorry, CI failed 🙈 I'll fix it🛠

**Comment by colorbox** [comment]
I fixed up 😃

**Comment by pocke** [comment]
Thank you!

**Comment by pocke** [comment]
I've released v0.1.2 https://rubygems.org/gems/ci_against/versions/0.1.2

**Pull request merged**
